project:
  type: website
  resources:
    - "*.html"
    - "*.css"
  post-render:
    - docs/project/add_catalogue_to_software.py

website:
  title: "Open Source Program Office | CERTH"
  navbar:
    # background: "#cfe1ed"
    left:
      - href: index.qmd
        text: Home
      - href: docs/index.qmd
        text: Technical Documentation
      - href: docs/project/software-en.qmd
        text: Software
      - href: contact.qmd
        text: Contact

    right:
      - text: "EN"
        href: index.qmd
      - icon: github
        href: https://github.com/ospo-certh/OSPO_CERTH

  sidebar:
    - id: docs
      title: "Technical Documentation"
      style: "docked"
      background: light
      contents:
        - text: "CERTH OSPO Technical Documentation"
          href: docs/index.qmd
        - section: "Key Concepts"
          contents:
            - text: "Copyright"
              href: docs/key-concepts/copyright.qmd
            - text: "Licensing"
              href: docs/key-concepts/licensing.qmd
            - text: "Due Diligence"
              href: docs/key-concepts/due-diligence.qmd
            - text: "What to Expect"
              href: docs/key-concepts/what-to-expect.qmd
        - section: "Recommendations"
          contents:
            - text: "Copyright and Licensing"
              href: docs/recommendations/licensing.qmd
        - section: "Submit Software"
          contents:
            - text: "Submit Your Software"
              href: docs/submit-software.qmd

    - id: docs-gr
      title: "Τεχνική Τεκμηρίωση"
      style: "docked"
      background: light
      contents:
        - text: "CERTH OSPO Τεχνική Τεκμηρίωση"
          href: docs-gr/index.qmd
        - section: "Βασικές Έννοιες"
          contents:
            - text: "Πνευματικά Δικαιώματα"
              href: docs-gr/key-concepts/copyright.qmd
            - text: "Αδειοδότηση"
              href: docs-gr/key-concepts/licensing.qmd
            - text: "Δέουσα Επιμέλεια"
              href: docs-gr/key-concepts/due-diligence.qmd
            - text: "Τι να Περιμένετε"
              href: docs-gr/key-concepts/what-to-expect.qmd
        - section: "Συστάσεις"
          contents:
            - text: "Πνευματικά Δικαιώματα και Αδειοδότηση"
              href: docs-gr/recommendations/licensing.qmd
        - section: "Υποβολή Λογισμικού"
          contents:
            - text: "Υποβάλετε το Λογισμικό σας"
              href: docs-gr/submit-software.qmd

  bread-crumbs: false

  page-footer:
    border: true
    left: "[License](https://github.com/ospo-certh/OSPO_CERTH/blob/main/LICENSE)"

editor: source

format:
  html:
    theme: [morph, sass/theme-light.scss]
    fig-format: svg
    toc: false
    include-in-header: js/lang-init.html
    include-after-body: js/lang-switch.html

knitr:
  opts_chunk:
    dev: svg
    dev.args: { bg: "transparent" }
