---
title: ""
format: html
editor: visual
---

::: {.custom-hero .column-screen}
:::



# Γραφείο Λογισμικού Ανοιχτού Κώδικα (OSPO) \| ΕΚΕΤΑ

Ο ανοιχτός κώδικας αναφέρεται στη δημόσια διάθεση του πηγαίου κώδικα έργων λογισμικού, η οποία προωθεί τη συνεισφορά και την επαναχρησιμοποίησή του από τρίτους. Η πρακτική αυτή είναι άρρηκτα συνδεδεμένη με την ανάπτυξη σύγχρονων τεχνολογιών, όπου σχεδόν όλοι οι οργανισμοί εξαρτώνται από τεχνολογίες που δημιουργούνται από την κοινότητα ανοιχτού κώδικα. Πέρα από την αξιοπιστία του δημόσιου ελέγχου, η στροφή προς το λογισμικό ανοιχτού κώδικα ενισχύεται από το αυξανόμενο κόστος δημιουργίας και τεχνικής υποστήριξης εμπορικού λογισμικού και υπηρεσιών, σε συνδυασμό με τη σημασία της ψηφιακής κυριαρχίας (digital sovereignty).

Χαρακτηριστικά, το λειτουργικό σύστημα Linux, του οποίου οι διανομές εξυπηρετούν τους κορυφαίους 500 υπερυπολογιστές παγκοσμίως, είναι ανοιχτού κώδικα. Το ίδιο ισχύει και για τις περισσότερες εξελίξεις στον τομέα της Τεχνητής Νοημοσύνης (Artificial Intelligence - AI), οι οποίες επίσης βασίζονται σε δημοφιλείς πλατφόρμες ανοιχτού κώδικα, όπως PyTorch, TensorFlow, και Jupyter. Το λογισμικό ανοιχτού κώδικα είναι εξίσου σημαντικό σε τομείς όπως η Διαχείριση Μεγάλων Δεδομένων (Big Data), η Υπολογιστική Νέφους (Cloud Computing), και η Κυβερνοασφάλεια.

**Οπότε τι είναι το OSPO του ΕΚΕΤΑ;** Το γραφείο αυτό δρα ως μια οργανωτική διεπαφή για δράσεις ανοικτού κώδικα, παρέχοντας ετερογενείς οπτικές που συμπεριλαμβάνουν νομικές, οικονομικές, τεχνολογικές, και κοινοτικές οπτικές. Παρόμοια γραφεία αποτελούν εγκαθιδρυμένη πρακτική σε εταιρείες (όπως Microsoft και Google), δημόσιες δομές (όπως η κυβέρνηση της Γαλλίας), και διακυβερνητικούς οργανισμούς (όπως ΠΟΥ και CERN). Τέτοια γραφεία αποτελούν κέντρα ανταγωνιστικότητας για τις διεργασίες ανοικτού κώδικα οργανισμών, και είναι υπεύθυνα για τον ορισμό, υλοποίηση, και καθοδήγηση σχετικών πολιτικών και στρατηγικών.

## Οι δράσεις μας

Το Γραφείο Προγραμμάτων Ανοιχτού Κώδικα (OSPO) του ΕΚΕΤΑ αποτελεί σημείο εισόδου στην τεχνογνωσία ανοιχτού κώδικα μέσω μιας ανοικτής και συμπεριληπτικής υπηρεσίας, δρώντας συνεργατικά με όλα τα Ινστιτούτα, και παρέχοντας μια δημόσια διεπαφή για πιθανούς εταίρους και το ενδιαφερόμενο κοινό. Οι δράσεις μας περιλαμβάνουν εκδηλώσεις, επικοινωνία, υποστήριξη και εκπαίδευση καθ' όλη τη διάρκεια του έτους. Εξωτερικά αναλαμβάνουμε τους παρακάτω ρόλους:

- Διατήρηση **δημόσιας λίστας** των έργων λογισμικού του ΕΚΕΤΑ και παροχής τους μέσω αυτής της σελίδας.

- Απάντηση σε **ερωτήσεις** που απευθύνονται στη διοίκηση του ΕΚΕΤΑ για θέματα ανοιχτού κώδικα.

- Καθοδήγηση ενδιαφερόμενων προς **ευκαιρίες, έργα, και ειδικούς** του ΕΚΕΤΑ. Αυτό επιτυγχάνεται μέσω της δημόσιας λίστας έργων λογισμικού, δράσεων, εξωτερικών επικοινωνιών, της ιστοσελίδας αυτής, κτλ.


## Υποστήριξη

Εσωτερικά, στοχεύουμε στην καθοδήγηση και εκπαίδευση του προσωπικού του ΕΚΕΤΑ σχετικά με βέλτιστες πρακτικές, εργαλεία, άδειες χρήσης, εξελίξεις κτλ., για έργα ανοιχτού κώδικα. Συγκεκριμένα:

- Παρέχουμε **συστάσεις** για τη δημοσιοποίηση λογισμικού που αναπτύσσεται στο ΕΚΕΤΑ ως έργα λογισμικού ανοιχτού κώδικα. Αυτό περιλαμβάνει κατευθυντήριες γραμμές και βέλτιστες πρακτικές για τις τεχνικές πτυχές του διαμοιρασμού κώδικα (π.χ. πού να φιλοξενηθεί, ποιες υπηρεσίες να χρησιμοποιηθούν, κατάλληλη χρήση των υποδομών του ΕΚΕΤΑ, γενικά εργαλεία για ανοιχτό κώδικα όπως έλεγχοι συμμόρφωσης αδειών και τρόπος ρύθμισης δοκιμών ελέγχου).

- Διευκολύνουμε και ενισχύουμε τη **διάδοση** ανοιχτού κώδικα.

- **Συμβουλεύουμε** τη διοίκηση του ΕΚΕΤΑ για θέματα ανοιχτού κώδικα με αντίκτυπο στον οργανισμό.
