---
title: ""
format: html
editor: visual
---

::: {.custom-hero .column-screen}
:::

# Open Source Program Office \| CERTH

**Open source** refers to software whose source code is made publicly available, promoting contribution
and reuse by others. The practice is inextricably linked to the development of modern technologies 
and almost all organizations depend on technologies created by the open-source community. 
In addition to the reliability obtained by public auditing, the move towards open source software is
encouraged by the increasing acquisition and technical support costs of commercial software
and services, combined with concerns over digital sovereignty.

Characteristically, the Linux operating system, whose distributions power the world's 
top-500 supercomputers, is open source. The same holds true for nearly 
all advancements in the field of Artificial Intelligence (AI), which also rely on popular open-source 
platforms like PyTorch, TensorFlow, and Jupyter. Open source software is equally pivotal for sectors 
like Big Data Management, Cloud Computing, and Cybersecurity.

**So what is an Open Source Program Office (OSPO)?** It operates as a central interface for open-source-related 
activities throughout an organization, consolidating the requisite expertise from diverse perspectives,
including legal, financial, technical, and community standpoints. Such an office is an established practice 
in numerous corporations (such as Microsoft and Google), public entities (such as the Government of France), 
and intergovernmental organizations (such as the WHO and CERN). It functions as the center of competency 
for an organization's open-source operations and structure, and it is responsible for defining and 
implementing the strategies and policies that guide these endeavors.

## Our activities

The CERTH OSPO serves as an entry point to CERTH's open-source expertise by forming an open and inclusive service, 
operating collaboratively with all Institutes, and serving externally as a visible interface for potential partners 
and the interested public. Our activities encompass events, communication, support, and training throughout the year.
Externally, we assume the following roles:

- Maintain a **public directory** of CERTH's open source portfolio that is easily accessible via this website.

- Answer **inquiries** directed to CERTH management that pertain to open source.

- Guide interested parties **toward opportunities, projects, and experts** at CERTH. This is achieved through the public directory, events, external communications, the website, etc.


## Support

Internally, we aim to guide and train CERTH staff regarding best practices, tools, licensing, developments, etc., 
for open source projects. In particular, we:

- Provide **recommendations** for the release of software developed at CERTH as open-source projects. This includes guidelines and best practices concerning the technical aspects of designing and sharing code (e.g., hosting locations, appropriate services to utilize, proper use of CERTH infrastructures, general open source tools such as license compliance checks, and testing configuration methodologies).

- Facilitate and enhance the **dissemination** of open source.

- **Advise** CERTH management on open source matters that impact the organization.

