---
title: "Αδειοδότηση"
toc: true
---

Η επιλογή άδειας χρήσης είναι ένα από τα πιο σημαντικά βήματα κατά την έκδοση ενός έργου λογισμικού ως 
ανοιχτού κώδικα. Χωρίς αυτήν, το έργο υπάγεται από προεπιλογή στο μοντέλο πνευματικής ιδιοκτησίας 
«όλα τα δικαιώματα διατηρούνται», όπου τρίτοι δεν έχουν νομικό δικαίωμα να χρησιμοποιήσουν, αντιγράψουν, 
τροποποιήσουν, ή αναδιανείμουν τον κώδικά σας, ακόμη κι αν αυτός είναι δημόσια ορατός σε κάποιο αποθετήριο. 
Οι άδειες χρήσης είναι αυτές που παραχωρούν συγκεκριμένα νομικά δικαιώματα πάνω στον κώδικα. Παράλληλα, σας 
προστατεύουν από αθέμιτη χρήση ή ζημίες λόγω σφαλμάτων, απορρίπτοντας οποιαδήποτε ευθύνη.

Οι διαδικασίες εφαρμογής μιας άδειας χρήσης σε λογισμικό που αναπτύσσεται στο ΕΚΕΤΑ παρουσιάζονται στις
[συστάσεις αδειοδότησης](../recommendations/licensing.qmd). Υπενθυμίζεται ότι το ΕΚΕΤΑ είναι ο κάτοχος 
των πνευματικών δικαιωμάτων του λογισμικού που παράγεται κατά τη διάρκεια ερευνητικών και αναπτυξιακών δραστηριοτήτων. 
Ωστόσο, η ακριβής άδεια πρέπει να επιλέγεται ανά έργο, δεδομένου ότι πρέπει να συμμορφώνεται με άδειες εξαρτώμενου 
λογισμικού, ενώ επηρεάζει την εξωτερική υιοθέτηση. Για παράδειγμα, ορισμένες άδειες απαγορεύουν τη χρήση κώδικα σε 
έργα μη ανοιχτού κώδικα (βλπ. παρακάτω).

Στη συνέχεια παρουσιάζονται δημοφιλείς άδειες χρήσης. Αυτές τυπικά κατηγοριοποιούνται ως προς τον βαθμό επιτρεπτικότητάς
τους, χωρίς όμως άδειες της ίδιας κατηγορίας να είναι απαραίτητα συμβατές μεταξύ τους. Για παράδειγμα, κώδικας που
υπάγεται σε άδεια Apache-2.0 μπορεί να χρησιμοποιηθεί εντός έργων BSD-3-Clause μόνο εφόσον τα τελευταία
τηρούν τις νομικές απαιτήσεις της Apache-2.0. Για αυτόν τον λόγο, μπορεί να συναντήσετε και έργα μεικτής αδειοδότησης, όπου 
διαφορετικά τμήματα του κώδικα διέπονται από διαφορετικές άδειες. Παρόλα αυτά, τα περισσότερα έργα προσπαθούν να παραμείνουν 
σε μία μόνο άδεια για λόγους απλότητας.

### Επιτρεπτικές άδειες

Παραδείγματα: [Apache-2.0](https://opensource.org/license/apache-2-0/),
[BSD-3-Clause](https://opensource.org/license/bsd-3-clause/), [MIT](https://opensource.org/license/mit/).

Αν αδειοδοτήσετε τον κώδικά σας με τέτοιον τρόπο, τότε οποιοσδήποτε μπορεί να τον επαναχρησιμοποιήσει, 
να τον τροποποιήσει/συνδυάσει με δικό του κώδικα, και να διανείμει το αποτέλεσμα. Αρκεί να τηρηθούν κάποιες 
βασικές προϋποθέσεις, όπως η συμπερίληψη της αρχικής σας σημείωσης πνευματικών δικαιωμάτων σε τυχόν διανεμόμενο 
λογισμικό.

Ανάμεσα στις ελευθερίες που παραχωρείτε όταν χρησιμοποιείτε επιτρεπτικές άδειες είναι η ελευθερία τροποποίησης 
του λογισμικού σας χωρίς να χρειάζεται το αποτέλεσμα να διανεμηθεί ως ανοιχτός κώδικας. Δηλαδή, τρίτοι 
(π.χ. μια εταιρεία) μπορούν να δημιουργήσουν ιδιόκτητα προϊόντα βασισμένα στον κώδικά σας. Τα περισσότερα 
ακαδημαϊκά έργα λογισμικού επιλέγουν μεταξύ των αδειών Apache-2.0 και MIT, καθώς αυτές εφαρμόζονται πολύ
εύκολα.

### Ασθενώς αμοιβαίες άδειες

Παραδείγματα: [LGPL-3.0](https://opensource.org/license/lgpl-3-0/),
[LGPL-2.1](https://opensource.org/license/lgpl-2-1/), [MPL-2.0](https://opensource.org/license/mpl-2-0/).

Αν αδειοδοτήσετε το έργο σας με αυτόν τον τύπο άδειας και κάποιος συνδυάσει τον πηγαίο κώδικά σας με δικό
του, κατά τη διανομή του τελευταίου θα πρέπει επίσης να αποκαλύψει και τον δικό σας κώδικα και άδεια. 
Αυτή η απαίτηση περιλαμβάνει και τη διανομή ό,ποιων τροποποιήσεων εφαρμόστηκαν στον κώδικά σας. Ωστόσο, 
ο νέος κώδικας μπορεί να μην αποκαλύψει τις δικές του πηγές. Τελικά, με αυτόν τον τρόπο επωφελείστε 
από βελτιώσεις τρίτων στον κώδικά σας.

Πολλές άδειες αντιμετωπίζουν διαφορετικά την επαναχρησιμοποίηση κώδικα από τη δυναμική σύνδεση (linking) 
με μεταγλωττισμένα δυαδικά αρχεία (η δυναμική σύνδεση αναφέρεται στην κλήση εξωτερικού λογισμικού κατά την
εκτέλεση ενός προγράμματος, γνωρίζοντας μόνο τις προγραμματιστικές διεπαφές κατά τη συγγραφή του κώδικα). Για 
παράδειγμα, κάποιος μπορεί να κυκλοφορήσει ένα ιδιόκτητο πρόγραμμα που συνδέεται με μια βιβλιοθήκη LGPL-3.0, 
εφόσον δεν τη διανέμει ο ίδιος. Σε αυτήν την περίπτωση, οι χρήστες του προγράμματος θα πρέπει να εγκαταστήσουν 
τη βιβλιοθήκη ξεχωριστά στο σύστημά τους.

### Ισχυρά αμοιβαίες άδειες

Παραδείγματα: [GPL-3.0](https://opensource.org/license/gpl-3-0/) και
[GPL-2.0](https://opensource.org/license/gpl-2-0/).

Αν αδειοδοτήσετε το έργο σας με τέτοια άδεια και κάποιος διανείμει λογισμικό που χρησιμοποιεί τον κώδικά σας 
συνδυασμένο με δικό του, θα πρέπει να διανείμει υπό την ίδια άδεια όχι μόνο τον δικό σας κώδικα 
(τροποποιημένο ή μη), αλλά και τον δικό του κώδικα.

Το όραμα των δημιουργών της GPL ήταν η δημιουργία ενός αυξανόμενου όγκου ελεύθερου λογισμικού, 
υποχρεώνοντας/προσκαλώντας τους χρήστες του στην παραγωγή επίσης ελεύθερου λογισμικού. Για αυτόν τον
λόγο, συχνά αναφέρεται ως ιική (viral) άδεια.
